# Generated by Django 5.2.6 on 2026-03-16 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity', models.FloatField(help_text='Equity percentage')),
                ('valuation', models.DecimalField(decimal_places=2, help_text='Post-money valuation', max_digits=12)),
                ('round', models.CharField(choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C+')], max_length=20)),
                ('investment_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('current_valuation', models.DecimalField(blank=True, decimal_places=2, help_text='Current valuation for ROI calculation', max_digits=12, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='startups.startup')),
            ],
        ),
    ]
