# Generated by Django 5.2.6 on 2026-03-16 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('ecommerce', 'E-commerce'), ('other', 'Other')], max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('growth', 'Growth Stage')], max_length=20)),
                ('founding_date', models.DateField()),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startups/logos/')),
                ('location', models.CharField(max_length=100)),
                ('team_size', models.IntegerField(default=1)),
                ('market', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_startups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
