# Generated by Django 5.2.6 on 2026-03-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_round', models.CharField(choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C+')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_offered', models.FloatField(blank=True, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pitch', models.TextField()),
                ('use_of_funds', models.TextField()),
                ('milestones', models.TextField()),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='funding/pitch_decks/')),
                ('financials', models.FileField(blank=True, null=True, upload_to='funding/financials/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('funded', 'Funded')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_applications', to='startups.startup')),
            ],
        ),
    ]
